const data = [
  { id:'1',
  name: 'Known-Unknown',
  size:'24 x 24 inches',
  year:"2021",
  medium:'Acrylic on Canvas',
  url:'/artworks/1 (20).png',
},
{ id:'2',
  name: 'The Angels Meet',
  size:'24 x 24 inches',
  year:"2021",
  medium:'Acrylic on Canvas',
  url:'/artworks/1 (21).png',
},
{ id:'3',
  name: 'Despair',
  size:'24 x 24 inches',
  year:"2021",
  medium:'Acrylic on Canvas',
  url:'/artworks/1 (22).png',
},
{ id:'4',
  name: 'UNTITLED',
  size:'72 x 24 inches',
  year:"2023",
  medium:'Acrylic on Canvas',
  url:'/artworks/1 (33).png',
},
{ id:'5',
  name: 'Once a Lunar Eclips',
  size:'24 x 24 inches',
  year:"2021",
  medium:'Acrylic on Canvas',
  url:'/artworks/1 (19).png',
},
{ id:'6',
  name: '1000 miles',
  size:'72 x 46 inches',
  year:"2020",
  medium:'Dry Pastel on Paper',
  url:'/artworks/1 (18).png',
},
{ id:'7',
  name: 'Migration',
  size:'5 x 8 feet',
  year:"2019",
  medium:'Mixed Media on Paper',
  url:'/artworks/1 (17).png',
},
{ id:'8',
  name: 'untitled I',
  size:'4 x 4 inches',
  year:"2019",
  medium:'Mixed Media on Paper',
  url:'/artworks/1 (16).png',
},
{ id:'9',
  name: 'untitled II',
  size:'48 x 48 inches',
  year:"2019",
  medium:'Mixed Media on Paper',
  url:'/artworks/1 (15).png',
},
{ id:'10',
  name: 'untitled I',
  size:'10 x 10 inches',
  year:"2019",
  medium:'Acrylic on Canvas',
  url:'/artworks/1 (10).png',
},
{ id:'11',
  name: 'untitled II',
  size:'10 x 10 inches',
  year:"2019",
  medium:'Acrylic on Canvas',
  url:'/artworks/1 (7).png',
},
{ id:'12',
  name: 'untitled III',
  size:'10 x 10 inches',
  year:"2019",
  medium:'Acrylic on Canvas',
  url:'/artworks/1 (13).png',
},
{ id:'13',
  name: 'untitled IV',
  size:'10 x 10 inches',
  year:"2019",
  medium:'Acrylic on Canvas',
  url:'/artworks/1 (14).png',
},
{ id:'14',
  name: 'untitled V',
  size:'10 x 10 inches',
  year:"2019",
  medium:'Acrylic on Canvas',
  url:'/artworks/1 (6).png',
},
{ id:'15',
  name: 'untitled VI',
  size:'10 x 10 inches',
  year:"2019",
  medium:'Acrylic on Canvas',
  url:'/artworks/1 (9).png',
},
{ id:'16',
  name: 'untitled VIII',
  size:'10 x 10 inches',
  year:"2019",
  medium:'Acrylic on Canvas',
  url:'/artworks/1 (11).png',
},
{ id:'17',
  name: 'untitled IX',
  size:'10 x 10 inches',
  year:"2019",
  medium:'Acrylic on Canvas',
  url:'/artworks/1 (12).png',
},
{ id:'18',
  name: 'untitled X',
  size:'10 x 10 inches',
  year:"2019",
  medium:'Acrylic on Canvas',
  url:'/artworks/1 (8).png',
},
{ id:'19',
  name: 'together',
  size:'24 x 24 inches',
  year:"2017",
  medium:'Acrylic on Canvas',
  url:'/artworks/1 (1).png',
},
{ id:'20',
  name: 'Journey',
  size:'36 x 48 inches',
  year:"2017",
  medium:'Acrylic on Canvas',
  url:'/artworks/1 (2).png',
},
{ id:'21',
  name: 'Worshippers',
  size:'48 x 36 inches',
  year:"2017",
  medium:'Acrylic on Canvas',
  url:'/artworks/1 (3).png',
},
{ id:'22',
  name: 'Dreamers',
  size:'48 x 36 inches',
  year:"2017",
  medium:'Acrylic on Canvas',
  url:'/artworks/1 (5).png',
},
]

export default data;